#! /usr/bin/env python3
# coding: utf-8
from tkinter import * // importer tkinter
import sqlite3 // importer sqlite3

fenetre = Tk()// widget racine tk 

def open_app(): // création de fonction qui permet de transformer open_app en _app
	
	Toplevel(_app())
	

def _fenetre():
	fenetre.title("SmartFit")
	fenetre.geometry("720x480")
	fenetre.minsize(480, 360)
	fenetre.config(background='#020000')




	# creer la frame
	frame = Frame(fenetre, bg='#020000')
	label_title = Label(frame, text="Bienvenue sur SmartFit", font=("Arial",  40), bg='#020000', fg='white')
	label_title.pack()
	label_subtitle = Label(frame, text="Votre application de coach sportif", font=("Arial",  25), bg='#020000', fg='white')
	label_subtitle.pack()
	button = Button(frame, text="Lancez-Vous",font=("Arial",  15), bg='white', fg='#020000', command=fenetre.destroy)
	button.pack(pady=25, fill=X)
	frame.pack(expand=YES)
	photo= PhotoImage(file="muscu.gif")
	zone_dessin = Canvas(fenetre,width=500,height=300,bg='#020000')
	zone_dessin.create_image(240, 150, image=photo)
	zone_dessin.pack()

	fenetre.mainloop()

def register_user():

	username_info = username.get()
	password_info = password.get()

	file=open(username_info+".txt", "w")
	file.write(username_info)
	file.write(password_info)
	file.close()

	username_entry.delete(0, END)
	password_entry.delete(0, END)

	Label(text = "Registration Sucess")

def register():
	screen1 = Toplevel(screen)
	screen.title("Register")
	screen1.geometry("300x250")

	global username
	global password
	username = StringVar()
	password = StringVar()

	Label(screen1, text = "Veuillez remplir ces informations").pack()
	Label(screen1, text = "").pack()
	Label(screen1, text = "Nom d'utilisateur * ").pack()
	username_entry = Entry(screen1, textvariable = username).pack()
	Label(screen1, text = "Password * ").pack()
	password_entry = Entry(screen1, textvariable = password).pack()
	Button(text='Connexion',width=20,bg='red',fg='white', command=open_app).place(x=180,y=680)
	Label(screen1, text = "").pack()
	Label(screen1, text = "Register", width = 10,height = 1,command = register_user).pack()
	

def login():
	root = Tk()
	root.geometry('500x730')
	root.title("Page d'Insrciption")

	label_0 = Label(root, text="Page d'Insrciption",width=20,font=("bold", 20))
	label_0.place(x=90,y=53)

	label_1 = Label(root, text="Nom d'Utilisateur",width=20,font=("bold", 10))
	label_1.place(x=80,y=130)

	entry_1 = Entry(root)
	entry_1.place(x=240,y=130)

	label_2 = Label(root, text="Email",width=20,font=("bold", 10))
	label_2.place(x=68,y=180)

	entry_2 = Entry(root)
	entry_2.place(x=240,y=180)

	label_2 = Label(root, text="Numéro de Téléphone",width=20,font=("bold", 10))
	label_2.place(x=68,y=230)

	entry_2 = Entry(root)
	entry_2.place(x=240,y=230)

	label_3 = Label(root, text="Mot De passe",width=20,font=("bold", 10))
	label_3.place(x=70,y=280)

	entry_3 = Entry(root)
	entry_3.place(x=240,y=280)

	label_4 = Label(root, text="Taille",width=20,font=("bold", 10))
	label_4.place(x=70,y=330)

	entry_4 = Entry(root)
	entry_4.place(x=240,y=330,)

	label_5 = Label(root, text="Poids",width=20,font=("bold", 10))
	label_5.place(x=70,y=380)

	entry_5 = Entry(root)
	entry_5.place(x=240,y=380,)

	label_6 = Label(root, text="Date De Naissance",width=20,font=("bold", 10))
	label_6.place(x=70,y=430)

	list1 = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list1)
	droplist.config(width=5)
	c.set('Jour')
	droplist.place(x=240,y=430)

	list2 = ['1','2','3','4','5','6','7','8','9','10','11','12'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list2)
	droplist.config(width=5)
	c.set('Mois')
	droplist.place(x=290,y=430)

	list3 = ['1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list3)
	droplist.config(width=5)
	c.set('Année')
	droplist.place(x=340,y=430)

	label_7 = Label(root, text="Sexe",width=20,font=("bold", 10))
	label_7.place(x=70,y=480)
	var = IntVar()
	Radiobutton(root, text="Homme",padx = 5, variable=var, value=1).place(x=215,y=480)
	Radiobutton(root, text="Femme",padx = 20, variable=var, value=2).place(x=290,y=480)

	label_8 = Label(root, text="Pays",width=20,font=("bold", 10))
	label_8.place(x=70,y=530)

	list4 = ['Canada','France','Angleterre','Allemagne','Espagne','Portugal','Belgique','Italie'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list4)
	droplist.config(width=15)
	c.set('Choix Du Pays')
	droplist.place(x=240,y=530)

	label_9 = Label(root, text="Niveau",width=20,font=("bold", 10))
	label_9.place(x=70,y=580)

	list5 = ['Débutant','Intermédiaire','Avancé','Expert'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list5)
	droplist.config(width=15)
	c.set('Choix Niveau')
	droplist.place(x=240,y=580)

	label_10 = Label(root, text="Objectifs",width=20,font=("bold", 10))
	label_10.place(x=70,y=630)

	list5 = ['Perte de Poids','Tonification','Prise de Masse','Affinement'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list5)
	droplist.config(width=15)
	c.set('Choix')
	droplist.place(x=240,y=630)


	Button(root, text='Envoyer',width=20,bg='red',fg='white', command=open_app).place(x=180,y=680)



def main_screen():
	global screen
	screen = Tk()
	screen.geometry("720x480")
	screen.title("SmartFit")
	Label(text = "SmartFit", bg = "grey", width = "300", height = "2", font = ("Calibri", 13)).pack()
	Label(text = "").pack()
	Button(text = "Inscription", height = "2", width = "30", command = login).pack()
	Label(text = "").pack()
	Button(text = "Connexion", height = "2", width = "30", command = register).pack()

	screen.mainloop()


def show_about():
	about_window = Toplevel()
	about_window.title("Support Technique")
	lb = Label(about_window, text="Si vous avez besoin de réponse à vos \n questions vous pouvez nous contactez sur notre adresse mail: \n smartfit_groupe4@gmail.com")
	lb.pack()


def _app():
#Création de la fenê^tre + paramètrage
	app = Tk()
	app.geometry("840x680")
	app.title("SmartFit")
	app.config(background='#020000')
	app.minsize(480, 360)

	#widgets...
	mainmenu = Menu(app)

	first_menu = Menu(mainmenu, tearoff=0)
	first_menu.add_command(label="Option1")
	first_menu.add_command(label="Option2")
	first_menu.add_command(label="Quitter", command=app.quit)

	second_menu = Menu(mainmenu, tearoff=0)
	second_menu.add_command(label="Exercice Complet Du Corps")
	second_menu.add_command(label="Exercice D'abdos")
	second_menu.add_command(label="Exercice Fesses")
	second_menu.add_command(label="Exercice Bras")
	second_menu.add_command(label="Exercice Jambes")
	second_menu.add_command(label="Support Technique", command=show_about)

	troisième_menu = Menu(mainmenu, tearoff=0)
	troisième_menu.add_command(label="Commande1")
	troisième_menu.add_command(label="Support Technique", command=show_about)

	quatrième_menu = Menu(mainmenu, tearoff=0)
	quatrième_menu.add_command(label="Niveau débutant")
	quatrième_menu.add_command(label="Niveau Intermédiaire")
	quatrième_menu.add_command(label="Niveau Avancé")
	quatrième_menu.add_command(label="Niveau Expert")
	quatrième_menu.add_command(label="Support Technique", command=show_about)

	mainmenu.add_cascade(label="Accueil", menu=first_menu)
	mainmenu.add_cascade(label="Exercice", menu=second_menu)
	mainmenu.add_cascade(label="Nutrition", menu=troisième_menu)
	mainmenu.add_cascade(label="Cardio", menu=quatrième_menu)

	

	# Boucle principale
	app.config(menu=mainmenu)
	app.mainloop()

if __name__=="__main__":
	_fenetre()
	main_screen()
