#! /usr/bin/env python3
# coding: utf-8
from tkinter import * #importer tkinter
import sqlite3 # importer sqlite3 pour lire la base de donnée

fenetre = Tk() #racine  principal tkinter qui permet de créer la fenêtre

def _fenetre(): #créer une fenetre pour la page d'accueil de l'application
	fenetre.title("SmartFit") #titre de la fenetre 
	fenetre.geometry("720x480") #taille de la fenetre 
	fenetre.minsize(480, 360) #taille minimum de la fenetre
	fenetre.config(background='#020000') #couleur de fond de la fenetre




	# creer la frame
	frame = Frame(fenetre, bg='#020000') #création d'une frame qui permet d'insérer des widgets
	label_title = Label(frame, text="Bienvenue sur SmartFit", font=("Arial",  40), bg='#020000', fg='white') #zone de texte et ses paramètres
	label_title.pack() #permet de configurer le label au niveau géométrique
	label_subtitle = Label(frame, text="Votre application de coach sportif", font=("Arial",  25), bg='#020000', fg='white') #zone de texte et ses paramètres
	label_subtitle.pack()#permet de configurer le label au niveau géométrique
	button = Button(frame, text="Lancez-Vous",font=("Arial",  15), bg='white', fg='#020000', command=fenetre.destroy)# bouton insérer dans la frame avec sa configuration qui détruit la page lorsque l'on active le bouton
	button.pack(pady=25, fill=X)#permet de configurer le label au niveau géométrique
	frame.pack(expand=YES)#permet de configurer la frame au niveau géométrique
	photo= PhotoImage(file="muscu.gif") #permet d'insérer une image 
	zone_dessin = Canvas(fenetre,width=500,height=300,bg='#020000')#création d'une zone de dessin pour intégrer l'image
	zone_dessin.create_image(240, 150, image=photo)#revvoie l'image dans le canvas
	zone_dessin.pack()#permet de configurer le label au niveau géométrique

	fenetre.mainloop() #affichage de la fenetre

def register_user():

	username_info = username.get()
	password_info = password.get()

	file=open(username_info+".txt", "w")
	file.write(username_info)
	file.write(password_info)
	file.close()

	username_entry.delete(0, END)
	password_entry.delete(0, END)

	Label(text = "Registration Sucess")

def register(): #focntion fenetre d'inscription
	screen1 = Toplevel(screen) #on associe screen1 a screen
	screen.title("Register") #titre de la fenetre
	screen1.geometry("300x250") #taille de la fenetre

	global username
	global password
	username = StringVar()
	password = StringVar()

	Label(screen1, text = "Veuillez remplir ces informations").pack() #zone de texte 
	Label(screen1, text = "").pack() #permet de faire un espace entre les deux champs
	Label(screen1, text = "Nom d'utilisateur * ").pack() #zone de texte
	username_entry = Entry(screen1, textvariable = username).pack()
	Label(screen1, text = "Password * ").pack() #zone de texte 
	password_entry = Entry(screen1, textvariable = password).pack()
	Label(screen1, text = "").pack() #permet de faire un espace entre les deux champs
	Label(screen1, text = "Register", width = 10,height = 1,command = register_user).pack()
	

def login():
	root = Tk() #racine  principal tkinter qui permet de créer la fenêtre
	root.geometry('500x730') #taille de la fenetre
	root.title("Page d'Insrciption") #titre de la fenetre

	label_0 = Label(root, text="Page d'Insrciption",width=20,font=("bold", 20)) #zone de texte 
	label_0.place(x=90,y=53) #Décalage horizontal et vertical en pixels.

	label_1 = Label(root, text="Nom d'Utilisateur",width=20,font=("bold", 10))#zone de texte 
	label_1.place(x=80,y=130)#Décalage horizontal et vertical en pixels.

	entry_1 = Entry(root)
	entry_1.place(x=240,y=130)#Décalage horizontal et vertical en pixels.

	label_2 = Label(root, text="Email",width=20,font=("bold", 10))#zone de texte 
	label_2.place(x=68,y=180)#Décalage horizontal et vertical en pixels.

	entry_2 = Entry(root)
	entry_2.place(x=240,y=180)#Décalage horizontal et vertical en pixels.

	label_2 = Label(root, text="Numéro de Téléphone",width=20,font=("bold", 10))#zone de texte 
	label_2.place(x=68,y=230)#Décalage horizontal et vertical en pixels.

	entry_2 = Entry(root)
	entry_2.place(x=240,y=230)#Décalage horizontal et vertical en pixels.

	label_3 = Label(root, text="Mot De passe",width=20,font=("bold", 10))#zone de texte 
	label_3.place(x=70,y=280)#Décalage horizontal et vertical en pixels.

	entry_3 = Entry(root)
	entry_3.place(x=240,y=280)#Décalage horizontal et vertical en pixels.

	label_4 = Label(root, text="Taille",width=20,font=("bold", 10))#zone de texte 
	label_4.place(x=70,y=330)#Décalage horizontal et vertical en pixels.

	entry_4 = Entry(root)
	entry_4.place(x=240,y=330,)#Décalage horizontal et vertical en pixels.

	label_5 = Label(root, text="Poids",width=20,font=("bold", 10))#zone de texte 
	label_5.place(x=70,y=380)#Décalage horizontal et vertical en pixels.

	entry_5 = Entry(root)
	entry_5.place(x=240,y=380,)#Décalage horizontal et vertical en pixels.

	label_6 = Label(root, text="Date De Naissance",width=20,font=("bold", 10))#zone de texte 
	label_6.place(x=70,y=430)#Décalage horizontal et vertical en pixels.

	list1 = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30']; #permet de choisir le jour de nassance 
	c=StringVar()
	droplist=OptionMenu(root,c, *list1)#menu déroulant les chiffres
	droplist.config(width=5)#taille du menu déroulant
	c.set('Jour')
	droplist.place(x=240,y=430)#Décalage horizontal et vertical en pixels.

	list2 = ['1','2','3','4','5','6','7','8','9','10','11','12']; #affiche le mois de naissance
	c=StringVar()
	droplist=OptionMenu(root,c, *list2)#menu déroulant les mois 
	droplist.config(width=5)#taille du menu déroulant
	c.set('Mois')
	droplist.place(x=290,y=430)#Décalage horizontal et vertical en pixels.

	list3 = ['1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005']; #affiche les années de naissance 
	c=StringVar()
	droplist=OptionMenu(root,c, *list3)#menu déroulant les années
	droplist.config(width=5)#taille du menu déroulant
	c.set('Année')
	droplist.place(x=340,y=430)#Décalage horizontal et vertical en pixels.

	label_7 = Label(root, text="Sexe",width=20,font=("bold", 10))
	label_7.place(x=70,y=480)#Décalage horizontal et vertical en pixels.
	var = IntVar()
	Radiobutton(root, text="Homme",padx = 5, variable=var, value=1).place(x=215,y=480)#bouton a choix multiples
	Radiobutton(root, text="Femme",padx = 20, variable=var, value=2).place(x=290,y=480)#bouton a choix multiples

	label_8 = Label(root, text="Pays",width=20,font=("bold", 10))
	label_8.place(x=70,y=530)#Décalage horizontal et vertical en pixels.

	list4 = ['Canada','France','Angleterre','Allemagne','Espagne','Portugal','Belgique','Italie'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list4)#menu déroulant les pays 
	droplist.config(width=15)#taille du menu déroulant
	c.set('Choix Du Pays')
	droplist.place(x=240,y=530)#Décalage horizontal et vertical en pixels.

	label_9 = Label(root, text="Niveau",width=20,font=("bold", 10))
	label_9.place(x=70,y=580)#Décalage horizontal et vertical en pixels.

	list5 = ['Débutant','Intermédiaire','Avancé','Expert'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list5)#menu déroulant les difficultés
	droplist.config(width=15)#taille du menu déroulant
	c.set('Choix Niveau')
	droplist.place(x=240,y=580)#Décalage horizontal et vertical en pixels.

	label_10 = Label(root, text="Objectifs",width=20,font=("bold", 10))
	label_10.place(x=70,y=630)#Décalage horizontal et vertical en pixels.

	list5 = ['Perte de Poids','Tonification','Prise de Masse','Affinement'];
	c=StringVar()
	droplist=OptionMenu(root,c, *list5)#menu déroulant les programmes
	droplist.config(width=15)#taille du menu déroulant
	c.set('Choix')
	droplist.place(x=240,y=630)#Décalage horizontal et vertical en pixels.


	Button(root, text='Envoyer',width=20,bg='red',fg='white', command=_app).place(x=180,y=680) #bouton pour envoyer le dossier d'inscription et passer a la page d'accueil



def main_screen(): #fonction page affiché après l'accueil
	global screen
	screen = Tk() #racine tk
	screen.geometry("720x480") #taille 
	screen.title("SmartFit") #titre
	Label(text = "SmartFit", bg = "grey", width = "300", height = "2", font = ("Calibri", 13)).pack() #zone de texte et configuration
	Label(text = "").pack()#permet de configurer le label au niveau géométrique
	Button(text = "Inscription", height = "2", width = "30", command = login).pack()#bouton pour changer de page
	Label(text = "").pack() #permet de configurer le label au niveau géométrique
	Button(text = "Connexion", height = "2", width = "30", command = register).pack() #bouton pour changer de page

	screen.mainloop() #affichage


def show_about(): #fonction du support technique 
	about_window = Toplevel()
	about_window.title("Support Technique") #titre
	lb = Label(about_window, text="Si vous avez besoin de réponse à vos \n questions vous pouvez nous contactez sur notre adresse mail: \n smartfit_groupe4@gmail.com") #zone de texte
	lb.pack() #permet de configurer le label au niveau géométrique


def _app():
#Création de la fenê^tre + paramètrage
	app = Tk() #racine tk
	app.geometry("840x680") #taille
	app.title("SmartFit") #titre
	app.config(background='#020000') #couleur de fond
	app.minsize(480, 360) #taille minimum

	#widgets...
	mainmenu = Menu(app)

	first_menu = Menu(mainmenu, tearoff=0) #menu déroulant 
	first_menu.add_command(label="Option1") #sous-onlgets des pages
	first_menu.add_command(label="Option2") #sous-onlgets des pages
	first_menu.add_command(label="Quitter", command=app.quit) #bouton pour quitter l'app

	second_menu = Menu(mainmenu, tearoff=0) #menu déroulant 
	second_menu.add_command(label="Exercice Complet Du Corps") #sous-onlgets des pages
	second_menu.add_command(label="Exercice D'abdos") #sous-onlgets des pages
	second_menu.add_command(label="Exercice Fesses") #sous-onlgets des pages
	second_menu.add_command(label="Exercice Bras") #sous-onlgets des pages
	second_menu.add_command(label="Exercice Jambes") #sous-onlgets des pages
	second_menu.add_command(label="Support Technique", command=show_about) #accès au support technique

	troisième_menu = Menu(mainmenu, tearoff=0) #menu déroulant 
	troisième_menu.add_command(label="Commande1") #sous-onlgets des pages  
	troisième_menu.add_command(label="Support Technique", command=show_about) #accès au support technique

	quatrième_menu = Menu(mainmenu, tearoff=0) #menu déroulant 
	quatrième_menu.add_command(label="Niveau débutant") #sous-onlgets des pages 
	quatrième_menu.add_command(label="Niveau Intermédiaire") #sous-onlgets des pages
	quatrième_menu.add_command(label="Niveau Avancé") #sous-onlgets des pages
	quatrième_menu.add_command(label="Niveau Expert") #sous-onlgets des pages
	quatrième_menu.add_command(label="Support Technique", command=show_about) #accès au support technique

	mainmenu.add_cascade(label="Accueil", menu=first_menu) #titre des onglets
	mainmenu.add_cascade(label="Exercice", menu=second_menu) #titre des onglets
	mainmenu.add_cascade(label="Nutrition", menu=troisième_menu) #titre des onglets
	mainmenu.add_cascade(label="Cardio", menu=quatrième_menu) #titre des onglets

	

	# Boucle principale
	app.config(menu=mainmenu)
	app.mainloop() #affichage 

if __name__=="__main__":
	_fenetre() #affichage de fonction 
	main_screen()#affichage de fonction après la première
